spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static
server:
  port: 8080