spring:
  application:
    name: config-center
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/config_center?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JinggeSun/spring-cloud-config-files
          username: JinggeSun
          password: zuotian3yue5hao
          search-paths: /
          force-pull: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8888
logging:
  level:
    org.springframework.cloud.bus: debug
