server:
  port: 8888
# redis
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbone?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
logging:
  level:
    com:
      sun:
        learn:
          repository: debug
